export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const START_TRANSACTION = 'START_TRANSACTION'

export const AMOUNT_CHANGED = 'AMOUNT_CHANGED'
export const ACCOUNT_CHANGED = 'ACCOUNT_CHANGED'

export const SET_BALANCES = 'SET_BALANCES'
